name: Go Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  go-tests:
    runs-on: k8s-staging-nano

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Golang
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - run: go version

      - name: Run GARM Go Tests
        run: make test
